name: Feature Request
description: Suggest a feature that would improve streamrip
labels: enhancement
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Is the feature request related to a problem. Please describe it.
      description: e.g. I have an issue when...

  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the solution you would like. 
      description: A clear and concise description of what you want to happen. Add any considered drawbacks.

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
